name: Build and Deploy Angular App to S3
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: cd simple-app && npm ci
      - name: Build Angular App
        run: cd simple-app && npm run build
      - name: Deploy to S3
        run: |
          aws s3 cp --recursive --exclude "*.map" dist/simple-app/ s3://simple-money-tracker-fe/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}